In [4]:
import pandas as pd
import numpy as np

# Dateien importieren
df1 = pd.read_excel(r'C:\Users\User\Documents\DSI Weiterbildung_Data Analyste\Zwischenprojekt\Kaggle\Global AI Job Market & Salary Trends 2025\Projektdateien AI Jobmarkt 2024_2025\AI_Job_vacancies_2025_dataset.xlsx')    
df2 = pd.read_excel(r'C:\Users\User\Documents\DSI Weiterbildung_Data Analyste\Zwischenprojekt\Kaggle\Global AI Job Market & Salary Trends 2025\Projektdateien AI Jobmarkt 2024_2025\AI_Job_vacancies_2025_dataset 1.xlsx')

#df_all = pd.concat([df1, df2], ignore_index=True)

# pd.concat([df1, df2]) stapelt standardmäßig zeilenweise (axis=0) und hängt df2 unter df1
# ignore_index=True setzt den Index neu von 0 bis n‑1, um keine doppelte Indexnummern zu generieren

In [5]:
print(df1.head())
print(df1.info())

    job_id              job_title  salary_usd salary_currency  \
0  AI00001  AI Research Scientist       90376             USD
1  AI00002   AI Software Engineer       61895             USD
2  AI00003          AI Specialist      152626             USD
3  AI00004           NLP Engineer       80215             USD
4  AI00005          AI Consultant       54624             EUR

  experience_level employment_type company_location company_size  \
0               SE              CT            China            M
1               EN              CT           Canada            M
2               MI              FL      Switzerland            L
3               SE              FL            India            M
4               EN              PT           France            S

  employee_residence  remote_ratio  \
0              China            50
1            Ireland           100
2        South Korea             0
3              India            50
4          Singapore           100

                                   required_skills education_required  \
0         Tableau, PyTorch, Kubernetes, Linux, NLP           Bachelor
1  Deep Learning, AWS, Mathematics, Python, Docker             Master
2     Kubernetes, Deep Learning, Java, Hadoop, NLP          Associate
3                        Scala, SQL, Linux, Python                PhD
4                     MLOps, Java, Tableau, Python             Master

     industry posting_date application_deadline  job_description_length  \
0  Automotive   2024-10-18           2024-11-07                    1076
1       Media   2024-11-20           2025-01-11                    1268
2   Education   2025-03-18           2025-04-07                    1974
3  Consulting   2024-12-23           2025-02-24                    1345
4       Media   2025-04-15           2025-06-23                    1989

   benefits_score       company_name
0              59    Smart Analytics
1              52       TechCorp Inc
2              94    Autonomous Tech
3              86     Future Systems
4              66  Advanced Robotics
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   job_id                  15000 non-null  object
 1   job_title               15000 non-null  object
 2   salary_usd              15000 non-null  int64
 3   salary_currency         15000 non-null  object
 4   experience_level        15000 non-null  object
 5   employment_type         15000 non-null  object
 6   company_location        15000 non-null  object
 7   company_size            15000 non-null  object
 8   employee_residence      15000 non-null  object
 9   remote_ratio            15000 non-null  int64
 10  required_skills         15000 non-null  object
 11  education_required      15000 non-null  object
 12  industry                15000 non-null  object
 13  posting_date            15000 non-null  datetime64[ns]
 14  application_deadline    15000 non-null  datetime64[ns]
 15  job_description_length  15000 non-null  int64
 16  benefits_score          15000 non-null  int64
 17  company_name            15000 non-null  object
dtypes: datetime64[ns](2), int64(4), object(12)
memory usage: 2.1+ MB
None

In [7]:
print(df2.head())
print(df2.info())

    job_id                 job_title  salary_usd salary_currency  \
0  AI00001            Data Scientist      219728             USD
1  AI00002                Head of AI      230237             JPY
2  AI00003             Data Engineer      128890             EUR
3  AI00004  Computer Vision Engineer       96349             USD
4  AI00005         Robotics Engineer       63065             EUR

  experience_level employment_type company_location company_size  \
0               EX              PT           Sweden            M
1               EX              PT            Japan            L
2               EX              CT          Germany            S
3               MI              FL          Finland            L
4               EN              FT           France            S

  employee_residence  remote_ratio                     required_skills  \
0             Sweden             0  Python, Computer Vision, R, Docker
1              Japan            50  Kubernetes, MLOps, Tableau, Python
2            Germany           100  Spark, Scala, Hadoop, PyTorch, GCP
3            Finland            50       MLOps, Linux, Tableau, Python
4             France           100          R, Scala, SQL, GCP, Python

  education_required        industry posting_date application_deadline  \
0          Associate  Transportation   2024-09-23           2024-10-31
1           Bachelor  Transportation   2024-07-26           2024-09-12
2           Bachelor      Automotive   2025-01-19           2025-03-28
3                PhD      Automotive   2024-07-20           2024-09-06
4          Associate         Finance   2025-03-16           2025-05-09

   job_description_length  benefits_score           company_name
0                    1132              66           TechCorp Inc
1                    2299              85     Cloud AI Solutions
2                    1329              55  Quantum Computing Inc
3                    1132              68    Cognitive Computing
4                    2011              93      Advanced Robotics
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   job_id                  15000 non-null  object
 1   job_title               15000 non-null  object
 2   salary_usd              15000 non-null  int64
 3   salary_currency         15000 non-null  object
 4   experience_level        15000 non-null  object
 5   employment_type         15000 non-null  object
 6   company_location        15000 non-null  object
 7   company_size            15000 non-null  object
 8   employee_residence      15000 non-null  object
 9   remote_ratio            15000 non-null  int64
 10  required_skills         15000 non-null  object
 11  education_required      15000 non-null  object
 12  industry                15000 non-null  object
 13  posting_date            15000 non-null  datetime64[ns]
 14  application_deadline    15000 non-null  datetime64[ns]
 15  job_description_length  15000 non-null  int64
 16  benefits_score          15000 non-null  int64
 17  company_name            15000 non-null  object
dtypes: datetime64[ns](2), int64(4), object(12)
memory usage: 2.1+ MB
None

# beide Exceldateien untereinander zusammenfügen

In [8]:
df_all = pd.concat([df1, df2], ignore_index=True)

# pd.concat([df1, df2]) stapelt standardmäßig zeilenweise (axis=0) und hängt df2 unter df1
# ignore_index=True setzt den Index neu von 0 bis n‑1, um keine doppelte Indexnummern zu generieren

In [9]:
print(df_all.head())
print(df_all.info())

    job_id              job_title  salary_usd salary_currency  \
0  AI00001  AI Research Scientist       90376             USD
1  AI00002   AI Software Engineer       61895             USD
2  AI00003          AI Specialist      152626             USD
3  AI00004           NLP Engineer       80215             USD
4  AI00005          AI Consultant       54624             EUR

  experience_level employment_type company_location company_size  \
0               SE              CT            China            M
1               EN              CT           Canada            M
2               MI              FL      Switzerland            L
3               SE              FL            India            M
4               EN              PT           France            S

  employee_residence  remote_ratio  \
0              China            50
1            Ireland           100
2        South Korea             0
3              India            50
4          Singapore           100

                                   required_skills education_required  \
0         Tableau, PyTorch, Kubernetes, Linux, NLP           Bachelor
1  Deep Learning, AWS, Mathematics, Python, Docker             Master
2     Kubernetes, Deep Learning, Java, Hadoop, NLP          Associate
3                        Scala, SQL, Linux, Python                PhD
4                     MLOps, Java, Tableau, Python             Master

     industry posting_date application_deadline  job_description_length  \
0  Automotive   2024-10-18           2024-11-07                    1076
1       Media   2024-11-20           2025-01-11                    1268
2   Education   2025-03-18           2025-04-07                    1974
3  Consulting   2024-12-23           2025-02-24                    1345
4       Media   2025-04-15           2025-06-23                    1989

   benefits_score       company_name
0              59    Smart Analytics
1              52       TechCorp Inc
2              94    Autonomous Tech
3              86     Future Systems
4              66  Advanced Robotics
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   job_id                  30000 non-null  object
 1   job_title               30000 non-null  object
 2   salary_usd              30000 non-null  int64
 3   salary_currency         30000 non-null  object
 4   experience_level        30000 non-null  object
 5   employment_type         30000 non-null  object
 6   company_location        30000 non-null  object
 7   company_size            30000 non-null  object
 8   employee_residence      30000 non-null  object
 9   remote_ratio            30000 non-null  int64
 10  required_skills         30000 non-null  object
 11  education_required      30000 non-null  object
 12  industry                30000 non-null  object
 13  posting_date            30000 non-null  datetime64[ns]
 14  application_deadline    30000 non-null  datetime64[ns]
 15  job_description_length  30000 non-null  int64
 16  benefits_score          30000 non-null  int64
 17  company_name            30000 non-null  object
dtypes: datetime64[ns](2), int64(4), object(12)
memory usage: 4.1+ MB
None

# Zwischenstand_in Excel_Datei abspeichern

In [10]:
# in Excel-Datei abspeichern (index=False verhindert, dass der Pandas-Index(die linke Zahlen-Spalte beginnend bei 0 als extra Spalte in die Excel-Datei abspeichert) 

df_all.to_excel(r"C:\Users\User\Documents\DSI Weiterbildung_Data Analyste\Zwischenprojekt\Kaggle\Global AI Job Market & Salary Trends 2025\Projektdateien AI Jobmarkt 2024_2025\AI_Job_vacancies_2025_df_all.xlsx", index = False)

# Spalte Job-ID löschen und neue Indexspalte hinzufügen

In [11]:
# Spalte Job_Id löschen
# axis = 1 bedeutet, dass eine Spalte gelöscht wird


df = df_all.drop("job_id", axis = 1)

In [12]:
print(df.head())
print(df.info())

               job_title  salary_usd salary_currency experience_level  \
0  AI Research Scientist       90376             USD               SE
1   AI Software Engineer       61895             USD               EN
2          AI Specialist      152626             USD               MI
3           NLP Engineer       80215             USD               SE
4          AI Consultant       54624             EUR               EN

  employment_type company_location company_size employee_residence  \
0              CT            China            M              China
1              CT           Canada            M            Ireland
2              FL      Switzerland            L        South Korea
3              FL            India            M              India
4              PT           France            S          Singapore

   remote_ratio                                  required_skills  \
0            50         Tableau, PyTorch, Kubernetes, Linux, NLP
1           100  Deep Learning, AWS, Mathematics, Python, Docker
2             0     Kubernetes, Deep Learning, Java, Hadoop, NLP
3            50                        Scala, SQL, Linux, Python
4           100                     MLOps, Java, Tableau, Python

  education_required    industry posting_date application_deadline  \
0           Bachelor  Automotive   2024-10-18           2024-11-07
1             Master       Media   2024-11-20           2025-01-11
2          Associate   Education   2025-03-18           2025-04-07
3                PhD  Consulting   2024-12-23           2025-02-24
4             Master       Media   2025-04-15           2025-06-23

   job_description_length  benefits_score       company_name
0                    1076              59    Smart Analytics
1                    1268              52       TechCorp Inc
2                    1974              94    Autonomous Tech
3                    1345              86     Future Systems
4                    1989              66  Advanced Robotics
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   job_title               30000 non-null  object
 1   salary_usd              30000 non-null  int64
 2   salary_currency         30000 non-null  object
 3   experience_level        30000 non-null  object
 4   employment_type         30000 non-null  object
 5   company_location        30000 non-null  object
 6   company_size            30000 non-null  object
 7   employee_residence      30000 non-null  object
 8   remote_ratio            30000 non-null  int64
 9   required_skills         30000 non-null  object
 10  education_required      30000 non-null  object
 11  industry                30000 non-null  object
 12  posting_date            30000 non-null  datetime64[ns]
 13  application_deadline    30000 non-null  datetime64[ns]
 14  job_description_length  30000 non-null  int64
 15  benefits_score          30000 non-null  int64
 16  company_name            30000 non-null  object
dtypes: datetime64[ns](2), int64(4), object(11)
memory usage: 3.9+ MB
None

In [13]:
# Index-Spalte einfügen mit immer genau 5 Stellen um Datensätze immer genau zu identifzieren als stabiles ID-Feld

df.insert(0, 'ZeileNr', range(1, len(df) + 1))             
df['ZeileNr'] = df['ZeileNr'].astype(str).str.zfill(5)

print(df)

      ZeileNr                 job_title  salary_usd salary_currency  \
0       00001     AI Research Scientist       90376             USD
1       00002      AI Software Engineer       61895             USD
2       00003             AI Specialist      152626             USD
3       00004              NLP Engineer       80215             USD
4       00005             AI Consultant       54624             EUR
...       ...                       ...         ...             ...
29995   29996        AI Product Manager       39171             USD
29996   29997        AI Product Manager       77555             EUR
29997   29998             Data Engineer       28380             USD
29998   29999             AI Specialist       58764             EUR
29999   30000  Principal Data Scientist       58623             USD

      experience_level employment_type company_location company_size  \
0                   SE              CT            China            M
1                   EN              CT           Canada            M
2                   MI              FL      Switzerland            L
3                   SE              FL            India            M
4                   EN              PT           France            S
...                ...             ...              ...          ...
29995               MI              CT            China            M
29996               EN              CT      Netherlands            M
29997               EN              FL            India            M
29998               EN              PT           France            M
29999               SE              FT            China            M

      employee_residence  remote_ratio  \
0                  China            50
1                Ireland           100
2            South Korea             0
3                  India            50
4              Singapore           100
...                  ...           ...
29995              China            50
29996        Netherlands            50
29997              India            50
29998             France           100
29999              China             0

                                         required_skills education_required  \
0               Tableau, PyTorch, Kubernetes, Linux, NLP           Bachelor
1        Deep Learning, AWS, Mathematics, Python, Docker             Master
2           Kubernetes, Deep Learning, Java, Hadoop, NLP          Associate
3                              Scala, SQL, Linux, Python                PhD
4                           MLOps, Java, Tableau, Python             Master
...                                                  ...                ...
29995             Azure, R, NLP, Docker, Computer Vision                PhD
29996  Python, TensorFlow, Mathematics, AWS, Computer...                PhD
29997        Azure, Kubernetes, Spark, Statistics, MLOps          Associate
29998   MLOps, Statistics, Data Visualization, R, Python             Master
29999  AWS, Spark, Computer Vision, Data Visualizatio...                PhD

             industry posting_date application_deadline  \
0          Automotive   2024-10-18           2024-11-07
1               Media   2024-11-20           2025-01-11
2           Education   2025-03-18           2025-04-07
3          Consulting   2024-12-23           2025-02-24
4               Media   2025-04-15           2025-06-23
...               ...          ...                  ...
29995      Consulting   2025-01-07           2025-02-07
29996          Energy   2024-12-22           2025-02-12
29997      Government   2024-05-04           2024-05-21
29998     Real Estate   2024-05-08           2024-06-22
29999  Transportation   2024-11-23           2024-12-15

       job_description_length  benefits_score                company_name
0                        1076              59             Smart Analytics
1                        1268              52                TechCorp Inc
2                        1974              94             Autonomous Tech
3                        1345              86              Future Systems
4                        1989              66           Advanced Robotics
...                       ...             ...                         ...
29995                    1107              52             Smart Analytics
29996                    1870              97             Autonomous Tech
29997                    1558               9  Digital Transformation LLC
29998                     546              84  Machine Intelligence Group
29999                    1034              97       Quantum Computing Inc

[30000 rows x 18 columns]

# Check fehlende Werte pro Spalte, eindeutige Kategorien

In [15]:
print("\nFehlende Werte pro Spalte:")                       # wie viele Nullen habe ich pro Spalte in Summe
print(df.isnull().sum())

Fehlende Werte pro Spalte:
ZeileNr                   0
job_title                 0
salary_usd                0
salary_currency           0
experience_level          0
employment_type           0
company_location          0
company_size              0
employee_residence        0
remote_ratio              0
required_skills           0
education_required        0
industry                  0
posting_date              0
application_deadline      0
job_description_length    0
benefits_score            0
company_name              0
dtype: int64

In [17]:
eindeutige_kategorien = df['job_title'].unique()
print(eindeutige_kategorien)
df['job_title'].value_counts()

['AI Research Scientist' 'AI Software Engineer' 'AI Specialist'
 'NLP Engineer' 'AI Consultant' 'AI Architect' 'Principal Data Scientist'
 'Data Analyst' 'Autonomous Systems Engineer' 'AI Product Manager'
 'Machine Learning Engineer' 'Data Engineer' 'Research Scientist'
 'ML Ops Engineer' 'Robotics Engineer' 'Head of AI'
 'Deep Learning Engineer' 'Data Scientist' 'Machine Learning Researcher'
 'Computer Vision Engineer']

job_title
Machine Learning Engineer      1596
Machine Learning Researcher    1542
Autonomous Systems Engineer    1532
AI Architect                   1529
Robotics Engineer              1521
Data Engineer                  1518
AI Software Engineer           1514
AI Product Manager             1507
Computer Vision Engineer       1504
Deep Learning Engineer         1504
NLP Engineer                   1503
AI Specialist                  1502
Principal Data Scientist       1502
Data Analyst                   1493
Data Scientist                 1483
AI Research Scientist          1480
Research Scientist             1473
Head of AI                     1466
AI Consultant                  1417
ML Ops Engineer                1414
Name: count, dtype: int64

In [18]:
eindeutige_kategorien = df['company_location'].unique()
print(eindeutige_kategorien)
df['company_location'].value_counts()

['China' 'Canada' 'Switzerland' 'India' 'France' 'Germany'
 'United Kingdom' 'Singapore' 'Austria' 'Sweden' 'South Korea' 'Norway'
 'Netherlands' 'United States' 'Israel' 'Australia' 'Ireland' 'Denmark'
 'Finland' 'Japan']

company_location
Switzerland       1565
Germany           1560
Canada            1550
Denmark           1537
Singapore         1526
China             1523
France            1518
Israel            1509
United Kingdom    1509
Ireland           1507
United States     1500
Sweden            1481
Netherlands       1479
South Korea       1477
Japan             1475
Austria           1464
Norway            1460
India             1456
Australia         1453
Finland           1451
Name: count, dtype: int64

In [19]:
eindeutige_kategorien = df['employee_residence'].unique()
print(eindeutige_kategorien)
df['employee_residence'].value_counts()

['China' 'Ireland' 'South Korea' 'India' 'Singapore' 'Germany'
 'United Kingdom' 'France' 'Austria' 'Sweden' 'Norway' 'Israel'
 'United States' 'Netherlands' 'Denmark' 'Switzerland' 'Finland' 'Japan'
 'Canada' 'Australia' 'Poland' 'Vietnam' 'Belgium' 'Argentina' 'Hungary'
 'Luxembourg' 'Malaysia' 'Ghana' 'Portugal' 'Czech Republic' 'Philippines'
 'Italy' 'Estonia' 'Thailand' 'Colombia' 'Indonesia' 'Kenya' 'Chile'
 'Russia' 'South Africa' 'Spain' 'Turkey' 'Brazil' 'Romania' 'Ukraine'
 'Mexico' 'Egypt' 'Nigeria' 'New Zealand' 'Latvia']

employee_residence
Switzerland       1417
France            1417
China             1411
Canada            1402
India             1401
Ireland           1382
Denmark           1382
United Kingdom    1373
Sweden            1371
Germany           1365
Austria           1363
Singapore         1363
Netherlands       1355
South Korea       1342
United States     1337
Israel            1334
Australia         1334
Norway            1332
Japan             1300
Finland           1285
Romania            117
Argentina          106
Indonesia          104
Ukraine            102
Vietnam            102
Estonia            100
Russia              99
Turkey              99
New Zealand         98
South Africa        98
Mexico              96
Portugal            96
Brazil              95
Philippines         93
Belgium             91
Colombia            90
Malaysia            89
Thailand            88
Czech Republic      88
Poland              86
Luxembourg          86
Kenya               84
Hungary             83
Nigeria             82
Egypt               81
Italy               81
Ghana               80
Chile               78
Spain               78
Latvia              64
Name: count, dtype: int64

In [20]:
eindeutige_kategorien = df['required_skills'].unique()
print(eindeutige_kategorien)
df['required_skills'].value_counts()

['Tableau, PyTorch, Kubernetes, Linux, NLP'
 'Deep Learning, AWS, Mathematics, Python, Docker'
 'Kubernetes, Deep Learning, Java, Hadoop, NLP' ...
 'Azure, Kubernetes, Spark, Statistics, MLOps'
 'MLOps, Statistics, Data Visualization, R, Python'
 'AWS, Spark, Computer Vision, Data Visualization, Tableau']

required_skills
Python, TensorFlow, PyTorch                        25
Python, TensorFlow, Tableau                        18
Python, TensorFlow, Data Visualization             15
Python, TensorFlow, MLOps                          12
Linux, Python, TensorFlow                          12
                                                   ..
Git, Hadoop, R, Python, Spark                       1
Java, Scala, NLP, Docker, Computer Vision           1
Tableau, Spark, NLP, TensorFlow, PyTorch            1
Kubernetes, Deep Learning, Java, Hadoop, NLP        1
Deep Learning, AWS, Mathematics, Python, Docker     1
Name: count, Length: 25702, dtype: int64

In [21]:
eindeutige_kategorien = df['education_required'].unique()
print(eindeutige_kategorien)
df['education_required'].value_counts()

['Bachelor' 'Master' 'Associate' 'PhD']

education_required
Bachelor     7652
Associate    7473
PhD          7439
Master       7436
Name: count, dtype: int64

In [22]:
eindeutige_kategorien = df['industry'].unique()
print(eindeutige_kategorien)
df['industry'].value_counts()

['Automotive' 'Media' 'Education' 'Consulting' 'Healthcare' 'Gaming'
 'Government' 'Telecommunications' 'Manufacturing' 'Energy' 'Technology'
 'Real Estate' 'Finance' 'Transportation' 'Retail']

industry
Consulting            2041
Retail                2041
Automotive            2035
Government            2033
Technology            2022
Media                 2017
Real Estate           2012
Finance               2002
Manufacturing         1997
Telecommunications    1992
Healthcare            1981
Gaming                1966
Energy                1965
Education             1948
Transportation        1948
Name: count, dtype: int64

In [23]:
eindeutige_kategorien = df['company_name'].unique()
print(eindeutige_kategorien)
df['company_name'].value_counts()

['Smart Analytics' 'TechCorp Inc' 'Autonomous Tech' 'Future Systems'
 'Advanced Robotics' 'Neural Networks Co' 'DataVision Ltd'
 'Cloud AI Solutions' 'Quantum Computing Inc' 'Predictive Systems'
 'AI Innovations' 'Algorithmic Solutions' 'Cognitive Computing'
 'DeepTech Ventures' 'Machine Intelligence Group'
 'Digital Transformation LLC']

company_name
TechCorp Inc                  1920
Cognitive Computing           1920
Quantum Computing Inc         1918
Machine Intelligence Group    1908
AI Innovations                1893
Predictive Systems            1888
Digital Transformation LLC    1884
Cloud AI Solutions            1881
Future Systems                1880
DataVision Ltd                1872
Advanced Robotics             1870
Autonomous Tech               1861
DeepTech Ventures             1847
Neural Networks Co            1839
Smart Analytics               1814
Algorithmic Solutions         1805
Name: count, dtype: int64

# Alle Begriffe in den Spalten sind korrekt geschrieben - es gibt keine Abweichungen

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ZeileNr                 30000 non-null  object
 1   job_title               30000 non-null  object
 2   salary_usd              30000 non-null  int64
 3   salary_currency         30000 non-null  object
 4   experience_level        30000 non-null  object
 5   employment_type         30000 non-null  object
 6   company_location        30000 non-null  object
 7   company_size            30000 non-null  object
 8   employee_residence      30000 non-null  object
 9   remote_ratio            30000 non-null  int64
 10  required_skills         30000 non-null  object
 11  education_required      30000 non-null  object
 12  industry                30000 non-null  object
 13  posting_date            30000 non-null  datetime64[ns]
 14  application_deadline    30000 non-null  datetime64[ns]
 15  job_description_length  30000 non-null  int64
 16  benefits_score          30000 non-null  int64
 17  company_name            30000 non-null  object
dtypes: datetime64[ns](2), int64(4), object(12)
memory usage: 4.1+ MB

# Duplikate entfernen

In [26]:
duplikate = df.duplicated()
print(duplikate)

# Nur die duplizierten Zeilen sehen
print(df[duplikate])

# Anzahl Duplikate zählen
print(duplikate.sum())

0        False
1        False
2        False
3        False
4        False
         ...
29995    False
29996    False
29997    False
29998    False
29999    False
Length: 30000, dtype: bool
Empty DataFrame
Columns: [ZeileNr, job_title, salary_usd, salary_currency, experience_level, employment_type, company_location, company_size, employee_residence, remote_ratio, required_skills, education_required, industry, posting_date, application_deadline, job_description_length, benefits_score, company_name]
Index: []
0

# Ergebnis: keine Duplikate zu entfernen

# Gibt es ungewöhliche Werte?

In [27]:
# schauen ob die Daten Sinn manchen 

df.describe()

,salary_usd,remote_ratio,posting_date,application_deadline,job_description_length,benefits_score
count,30000.000000,30000.000000,30000,30000,30000.000000,30000.000000
mean,118670.451700,49.840000,2024-08-30 01:58:30.720000,2024-10-12 13:59:11.040000,1502.083667,68.400767
min,16621.000000,0.000000,2024-01-01 00:00:00,2024-01-16 00:00:00,500.000000,5.000000
25%,72575.750000,0.000000,2024-04-30 00:00:00,2024-06-14 00:00:00,1001.000000,58.000000
50%,103206.500000,50.000000,2024-08-30 00:00:00,2024-10-13 00:00:00,1512.000000,73.000000
75%,150921.750000,100.000000,2024-12-28 00:00:00,2025-02-10 00:00:00,1997.000000,86.000000
max,410273.000000,100.000000,2025-04-30 00:00:00,2025-07-11 00:00:00,2499.000000,99.000000
std,62229.977054,40.829278,NaN,NaN,575.418018,24.259334

In [ ]:
# der min-Wert von 16.621 $ finde ich ungewöhnlich - man muss hier schauen ob der Wert für eine Part-time Stelle ausgeschrieben wurde

In [33]:
df['posting_date'].dtype

dtype('<M8[ns]')

In [ ]:
# dtype('<M8[ns]') ist der korrekte Pandas-Datentyp für Datums-/Zeitwerte mit Nanosekunden-Präzision (datetime64[ns]). Es ist voll funktionsfähig für .dt.month, .dt.year und andere Extraktionen.

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ZeileNr                 30000 non-null  object
 1   job_title               30000 non-null  object
 2   salary_usd              30000 non-null  int64
 3   salary_currency         30000 non-null  object
 4   experience_level        30000 non-null  object
 5   employment_type         30000 non-null  object
 6   company_location        30000 non-null  object
 7   company_size            30000 non-null  object
 8   employee_residence      30000 non-null  object
 9   remote_ratio            30000 non-null  int64
 10  required_skills         30000 non-null  object
 11  education_required      30000 non-null  object
 12  industry                30000 non-null  object
 13  posting_date            30000 non-null  datetime64[ns]
 14  application_deadline    30000 non-null  datetime64[ns]
 15  job_description_length  30000 non-null  int64
 16  benefits_score          30000 non-null  int64
 17  company_name            30000 non-null  object
dtypes: datetime64[ns](2), int64(4), object(12)
memory usage: 4.1+ MB

# Neue Spalten mit posting_month und posting_year aus posting_date hinzufügen

In [45]:
df['posting_month'] = df['posting_date'].dt.month
df['posting_year'] = df['posting_date'].dt.year

In [46]:
df.head
print(df.head)

<bound method NDFrame.head of       ZeileNr                 job_title  salary_usd salary_currency  \
0       00001     AI Research Scientist       90376             USD
1       00002      AI Software Engineer       61895             USD
2       00003             AI Specialist      152626             USD
3       00004              NLP Engineer       80215             USD
4       00005             AI Consultant       54624             EUR
...       ...                       ...         ...             ...
29995   29996        AI Product Manager       39171             USD
29996   29997        AI Product Manager       77555             EUR
29997   29998             Data Engineer       28380             USD
29998   29999             AI Specialist       58764             EUR
29999   30000  Principal Data Scientist       58623             USD

      experience_level employment_type company_location company_size  \
0                   SE              CT            China            M
1                   EN              CT           Canada            M
2                   MI              FL      Switzerland            L
3                   SE              FL            India            M
4                   EN              PT           France            S
...                ...             ...              ...          ...
29995               MI              CT            China            M
29996               EN              CT      Netherlands            M
29997               EN              FL            India            M
29998               EN              PT           France            M
29999               SE              FT            China            M

      employee_residence  remote_ratio  ...        industry posting_date  \
0                  China            50  ...      Automotive   2024-10-18
1                Ireland           100  ...           Media   2024-11-20
2            South Korea             0  ...       Education   2025-03-18
3                  India            50  ...      Consulting   2024-12-23
4              Singapore           100  ...           Media   2025-04-15
...                  ...           ...  ...             ...          ...
29995              China            50  ...      Consulting   2025-01-07
29996        Netherlands            50  ...          Energy   2024-12-22
29997              India            50  ...      Government   2024-05-04
29998             France           100  ...     Real Estate   2024-05-08
29999              China             0  ...  Transportation   2024-11-23

      application_deadline job_description_length benefits_score  \
0               2024-11-07                   1076             59
1               2025-01-11                   1268             52
2               2025-04-07                   1974             94
3               2025-02-24                   1345             86
4               2025-06-23                   1989             66
...                    ...                    ...            ...
29995           2025-02-07                   1107             52
29996           2025-02-12                   1870             97
29997           2024-05-21                   1558              9
29998           2024-06-22                    546             84
29999           2024-12-15                   1034             97

                     company_name  posting_month posting_year  date_diff  \
0                 Smart Analytics             10         2024    20 days
1                    TechCorp Inc             11         2024    52 days
2                 Autonomous Tech              3         2025    20 days
3                  Future Systems             12         2024    63 days
4               Advanced Robotics              4         2025    69 days
...                           ...            ...          ...        ...
29995             Smart Analytics              1         2025    31 days
29996             Autonomous Tech             12         2024    52 days
29997  Digital Transformation LLC              5         2024    17 days
29998  Machine Intelligence Group              5         2024    45 days
29999       Quantum Computing Inc             11         2024    22 days

       date_diff_days
0                  20
1                  52
2                  20
3                  63
4                  69
...               ...
29995              31
29996              52
29997              17
29998              45
29999              22

[30000 rows x 22 columns]>

# Neue Spalte mit der Differrenz aus application_deadline und posting_date in Tagen

In [47]:
df['date_diff'] = df['application_deadline'] - df['posting_date']

In [43]:
df['date_diff_days'] = df['date_diff'].dt.days

In [48]:
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 22 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ZeileNr                 30000 non-null  object
 1   job_title               30000 non-null  object
 2   salary_usd              30000 non-null  int64
 3   salary_currency         30000 non-null  object
 4   experience_level        30000 non-null  object
 5   employment_type         30000 non-null  object
 6   company_location        30000 non-null  object
 7   company_size            30000 non-null  object
 8   employee_residence      30000 non-null  object
 9   remote_ratio            30000 non-null  int64
 10  required_skills         30000 non-null  object
 11  education_required      30000 non-null  object
 12  industry                30000 non-null  object
 13  posting_date            30000 non-null  datetime64[ns]
 14  application_deadline    30000 non-null  datetime64[ns]
 15  job_description_length  30000 non-null  int64
 16  benefits_score          30000 non-null  int64
 17  company_name            30000 non-null  object
 18  posting_month           30000 non-null  int32
 19  posting_year            30000 non-null  int32
 20  date_diff               30000 non-null  timedelta64[ns]
 21  date_diff_days          30000 non-null  int64
dtypes: datetime64[ns](2), int32(2), int64(5), object(12), timedelta64[ns](1)
memory usage: 4.8+ MB

,ZeileNr,job_title,salary_usd,salary_currency,experience_level,employment_type,company_location,company_size,employee_residence,remote_ratio,...,industry,posting_date,application_deadline,job_description_length,benefits_score,company_name,posting_month,posting_year,date_diff,date_diff_days
0,00001,AI Research Scientist,90376,USD,SE,CT,China,M,China,50,...,Automotive,2024-10-18,2024-11-07,1076,59,Smart Analytics,10,2024,20 days,20
1,00002,AI Software Engineer,61895,USD,EN,CT,Canada,M,Ireland,100,...,Media,2024-11-20,2025-01-11,1268,52,TechCorp Inc,11,2024,52 days,52
2,00003,AI Specialist,152626,USD,MI,FL,Switzerland,L,South Korea,0,...,Education,2025-03-18,2025-04-07,1974,94,Autonomous Tech,3,2025,20 days,20
3,00004,NLP Engineer,80215,USD,SE,FL,India,M,India,50,...,Consulting,2024-12-23,2025-02-24,1345,86,Future Systems,12,2024,63 days,63
4,00005,AI Consultant,54624,EUR,EN,PT,France,S,Singapore,100,...,Media,2025-04-15,2025-06-23,1989,66,Advanced Robotics,4,2025,69 days,69

In [49]:
del df['date_diff']

In [50]:
df.head()

,ZeileNr,job_title,salary_usd,salary_currency,experience_level,employment_type,company_location,company_size,employee_residence,remote_ratio,...,education_required,industry,posting_date,application_deadline,job_description_length,benefits_score,company_name,posting_month,posting_year,date_diff_days
0,00001,AI Research Scientist,90376,USD,SE,CT,China,M,China,50,...,Bachelor,Automotive,2024-10-18,2024-11-07,1076,59,Smart Analytics,10,2024,20
1,00002,AI Software Engineer,61895,USD,EN,CT,Canada,M,Ireland,100,...,Master,Media,2024-11-20,2025-01-11,1268,52,TechCorp Inc,11,2024,52
2,00003,AI Specialist,152626,USD,MI,FL,Switzerland,L,South Korea,0,...,Associate,Education,2025-03-18,2025-04-07,1974,94,Autonomous Tech,3,2025,20
3,00004,NLP Engineer,80215,USD,SE,FL,India,M,India,50,...,PhD,Consulting,2024-12-23,2025-02-24,1345,86,Future Systems,12,2024,63
4,00005,AI Consultant,54624,EUR,EN,PT,France,S,Singapore,100,...,Master,Media,2025-04-15,2025-06-23,1989,66,Advanced Robotics,4,2025,69

# Zwischenstand in Excel abspeichern

In [51]:
# in Excel-Datei abspeichern (index=False verhindert, dass der Pandas-Index(die linke Zahlen-Spalte beginnend bei 0 als extra Spalte in die Excel-Datei abspeichert) 

df.to_excel(r"C:\Users\User\Documents\DSI Weiterbildung_Data Analyste\Zwischenprojekt\Kaggle\Global AI Job Market & Salary Trends 2025\Projektdateien AI Jobmarkt 2024_2025\AI_Job_vacancies_2025_df.xlsx", index = False)

# Spalte required_skills splitten an allen Kommas und jeweils für jeden Begriff der Zeile ein neue Splate erstellen

In [55]:
#  df['...'].str.split(',\\s*', expand=True) an: Trennt bei Komma + optionalem Leerzeichen (regex \\s* vermeidet Leerzeichen-Probleme).
# expand=True erzeugt DataFrame mit Spalten 0,1,2,...


split_df = df['required_skills'].str.split(',\\s*', expand=True)
split_df.columns = ['required_skill_1', 'required_skill_2', 'required_skill_3', 'required_skill_4', 'required_skill_5']
df_split = pd.concat([df.drop('required_skills', axis=1), split_df], axis=1)

In [56]:
df_split.head()

,ZeileNr,job_title,salary_usd,salary_currency,experience_level,employment_type,company_location,company_size,employee_residence,remote_ratio,...,benefits_score,company_name,posting_month,posting_year,date_diff_days,required_skill_1,required_skill_2,required_skill_3,required_skill_4,required_skill_5
0,00001,AI Research Scientist,90376,USD,SE,CT,China,M,China,50,...,59,Smart Analytics,10,2024,20,Tableau,PyTorch,Kubernetes,Linux,NLP
1,00002,AI Software Engineer,61895,USD,EN,CT,Canada,M,Ireland,100,...,52,TechCorp Inc,11,2024,52,Deep Learning,AWS,Mathematics,Python,Docker
2,00003,AI Specialist,152626,USD,MI,FL,Switzerland,L,South Korea,0,...,94,Autonomous Tech,3,2025,20,Kubernetes,Deep Learning,Java,Hadoop,NLP
3,00004,NLP Engineer,80215,USD,SE,FL,India,M,India,50,...,86,Future Systems,12,2024,63,Scala,SQL,Linux,Python,None
4,00005,AI Consultant,54624,EUR,EN,PT,France,S,Singapore,100,...,66,Advanced Robotics,4,2025,69,MLOps,Java,Tableau,Python,None

# Zwischenstand in Excel abspeichern

In [57]:
# in Excel-Datei abspeichern (index=False verhindert, dass der Pandas-Index(die linke Zahlen-Spalte beginnend bei 0 als extra Spalte in die Excel-Datei abspeichert) 

df_split.to_excel(r"C:\Users\User\Documents\DSI Weiterbildung_Data Analyste\Zwischenprojekt\Kaggle\Global AI Job Market & Salary Trends 2025\Projektdateien AI Jobmarkt 2024_2025\AI_Job_vacancies_2025_df_split.xlsx", index = False)